# Generated by Django 5.0.4 on 2024-05-05 12:22

import datetime
import django_quill.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='content',
            field=django_quill.fields.QuillField(),
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 5, 12, 22, 17, 133280, tzinfo=datetime.timezone.utc), verbose_name='date published'),
        ),
    ]
