# Generated by Django 5.0.4 on 2024-05-04 03:38

import datetime
import django_quill.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_tutorial_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='content',
            field=django_quill.fields.QuillField(),
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 4, 3, 38, 12, 768305, tzinfo=datetime.timezone.utc), verbose_name='date published'),
        ),
    ]
