# Generated by Django 5.0.4 on 2024-05-05 12:44

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_tutorialcategory_alter_tutorial_published_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorial',
            name='series',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.tutorialseries', verbose_name='Series'),
        ),
        migrations.AddField(
            model_name='tutorial',
            name='slug',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 5, 12, 44, 19, 280487, tzinfo=datetime.timezone.utc), verbose_name='date published'),
        ),
    ]
