# Generated by Django 5.0.4 on 2024-05-05 12:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_tutorial_series_tutorial_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 5, 12, 44, 31, 615953, tzinfo=datetime.timezone.utc), verbose_name='date published'),
        ),
    ]
